In [2]:
import numpy as np

### ndarray object

In [2]:
a=[1,2,3,4,5,6]

In [3]:
print(a)

[1, 2, 3, 4, 5, 6]


In [4]:
print(type(a))

<class 'list'>


In [5]:
np_b = np.array(a)

In [6]:
print(np_b)

[1 2 3 4 5 6]


In [8]:
print(type(np_b))

<class 'numpy.ndarray'>


In [9]:
L = range(1000)
%timeit [i**2 for i in L]

178 µs ± 35.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
a=np.arange(1000)
%timeit a**2

2.49 µs ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Creating arrays

In [11]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [12]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 3)

In [19]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
c.ndim

3

In [21]:
c.shape

(2, 2, 2)

## Creating Numpy Arrays From a List

In [20]:
my_lst=[1,2,3,4,5]
my_lst

[1, 2, 3, 4, 5]

In [22]:
np.array(my_lst)

array([1, 2, 3, 4, 5])

In [23]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.array(my_matrix).shape

(3, 3)

## Functions for creating arrays

#### arange

In [26]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b=np.arange(1,15,3)
b

array([ 1,  4,  7, 10, 13])

#### Linespace

In [32]:
a = np.linspace(0,5,6)
a

array([0., 1., 2., 3., 4., 5.])

In [34]:
np.linspace(0,15,5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

#### Zeros and ones

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [7]:
a=np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
c = np.eye(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
d = np.eye(4,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [10]:
a=np.diag([2,4,5,7])
a

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [11]:
np.diag(a)

array([2, 4, 5, 7])

In [9]:
random_array = np.random.randint(1,171,7)
print(random_array)

[149 150  73 155  37  14 160]


In [10]:
a=np.random.rand(4)
a

array([0.20387658, 0.77872471, 0.36662375, 0.68340114])

In [8]:
a=np.random.randn(150)
a

array([ 0.73604229, -0.58382604, -0.95069912, -0.38383771,  0.17815039,
       -1.28616597, -1.7485705 ,  0.94533389,  0.18802287, -0.02903436,
       -0.039578  , -0.71313643, -0.70062068,  0.421688  , -0.18892571,
       -0.05781198,  1.49279593,  0.44879431, -0.97407663,  0.69983117,
       -0.3702013 , -1.65383177, -0.05378711, -0.77131551,  0.70378962,
        0.19095563, -0.54258516, -1.26367607,  1.96600236, -0.12441652,
       -0.10206433, -0.71958753,  1.38373615, -0.50587191, -0.91875416,
        1.26893952,  0.04925411, -0.36543918,  0.6222537 ,  0.91876907,
        0.06498756,  0.35219504, -0.31630541,  0.05303325,  1.3072995 ,
        0.62737911,  0.51776597, -0.25911167, -0.54164942,  0.167696  ,
        1.59653732,  1.47651997, -1.94156636,  1.1605001 , -0.04602558,
       -0.30342563, -1.67250523,  0.4181736 , -0.38921297, -1.6511966 ,
        0.7198744 , -0.15362196,  0.60271665, -0.0125847 ,  0.51117282,
       -1.25408792,  0.06953333, -1.2834548 ,  0.31810511, -0.65

### Copy array

In [12]:
a=np.array([1,5,8])
b=a
b[0]=100
print(a)
print(b)

[100   5   8]
[100   5   8]


### Reshape array

In [13]:
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [16]:
a1=arr.reshape(5,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
a = np.array([[3, 4, 6], [2, 1, 7]])
print(a)
print("Shape of a: {}".format(a.shape))


[[3 4 6]
 [2 1 7]]
Shape of a: (2, 3)


In [9]:
b=a.reshape(3,2)
print(b)
print("Shape of b: {}".format(b.shape))

[[3 4]
 [6 2]
 [1 7]]
Shape of b: (3, 2)


### Transpose array

In [27]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape: {}".format(a.shape))
print(a)

Shape: (2, 4)
[[1 2 3 4]
 [5 6 7 8]]


#### Flattening

In [29]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [30]:
c.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Sorting

In [31]:
a=np.array([[2,3,4],[5,6,7]])
b=np.sort(a,axis=1)
b

array([[2, 3, 4],
       [5, 6, 7]])

### Add/Remove operations on a numpy array

In [10]:
a=np.array([5,6,8])
a=np.append(a,[9,2,3])
print("Numpy array after addition:",a)

Numpy array after addition: [5 6 8 9 2 3]


### Indexing

In [13]:
a=np.arange(1,9)
print(a)
print(a[5])

[1 2 3 4 5 6 7 8]
6


In [15]:
a= np.diag([9,4,2])
print(a)
print(a[2,1])

[[9 0 0]
 [0 4 0]
 [0 0 2]]
0


In [16]:
a[2,1]=4
a

array([[9, 0, 0],
       [0, 4, 0],
       [0, 4, 2]])

### Slicing

In [17]:
a=np.arange(2,12)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
a[1:11:3]

array([3, 6, 9])

In [20]:
a=np.arange(12)
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
a[5:]=11
a

array([ 0,  1,  2,  3,  4, 11, 11, 11, 11, 11, 11, 11])

In [22]:
b=np.arange(3)
b

array([0, 1, 2])

### Fancy Indexing

In [28]:
a=np.random.randint(0 ,10, 2)

In [29]:
a

array([8, 5])

In [30]:
a[a%2==0]

array([8])

In [31]:
a[a%2==0]=-1
a

array([-1,  5])

#### Indexing with an array of integers

In [32]:
a=np.arange(0,99,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
a[[3,5,6]]

array([30, 50, 60])

In [36]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30, -200,   50,   60, -200,   80, -200])

## Operations

#### With scalars

In [38]:
a=np.array([1,2,3,4,5])
print(a)
print(a+1)

[1 2 3 4 5]
[2 3 4 5 6]


In [40]:
a ** 2

array([ 1,  4,  9, 16, 25])

#### All arithmetic operates elementwise

In [45]:
b= np.ones(4)+1
b

array([2., 2., 2., 2.])

In [51]:
a=np.array([[1,2,3],[4,5,6],[4,5,7]])
b=np.array([[3,4,5],[2,4,7],[9,6,3]])
print('sum of a and b : \n',a+b)

sum of a and b : 
 [[ 4  6  8]
 [ 6  9 13]
 [13 11 10]]


In [52]:
print('product of a and b :\n',a*b)

product of a and b :
 [[ 3  8 15]
 [ 8 20 42]
 [36 30 21]]


In [53]:
c=np.diag([1,2,3,4])
print(c * c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [56]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
b=np.array([[3,3,4],[5,6,7],[3,5,7]])
print('Matrix multiplication:\n',np.matmul(a,b))

Matrix multiplication:
 [[ 22  30  39]
 [ 44  58  75]
 [ 77 100 129]]


#### Comparisions

In [57]:
a=np.array([1,2,3,4])
b=np.array([5,6,8,3])
a==b

array([False, False, False, False])

In [58]:
a>b

array([False, False, False,  True])

In [59]:
a=np.array([3,4,6])
b=np.array([7,8,9])
c=np.array([5,7,4])

In [60]:
np.array_equal(a,b)

False

In [61]:
np.array_equal(a,c)

False

#### Logical Operations

In [65]:
a=np.array([0,1,2,3],dtype=bool)
b=np.array([8,6,2,3],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [66]:
np.logical_and(a, b)

array([False,  True,  True,  True])

#### Transcendental functions

In [67]:
a= np.arange(3)
np.sin(a)

array([0.        , 0.84147098, 0.90929743])

In [68]:
np.log(a)

C:\Users\Bablu\AppData\Local\Temp\ipykernel_5440\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [69]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

#### Shape Mismatch

In [70]:
a=np.arange(3)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Basic Reductions

#### computing sums

In [71]:
x=np.array([2,3,5,6])
np.sum(x)

16

In [73]:
x=np.array([[2,2],[3,3]])
x

array([[2, 2],
       [3, 3]])

In [74]:
x.sum(axis=0)

array([5, 5])

In [77]:
x.sum(axis=1)

array([4, 6])

#### Other reductions

In [78]:
x=np.array([1,3,5])
x.min()

1

In [80]:
x.max()

5

In [81]:
x.argmin()

0

In [83]:
x.argmax()

2

#### Statistics

In [88]:
normal_array=np.arange(0,12,2)
print('Array is',format(normal_array))

### min
print('min element is',np.min(normal_array))

### max
print('max element is',np.max(normal_array))

### sum
print('sum of elements in array is',np.sum(normal_array))

### mean
print('mean of element in array is',np.mean(normal_array))

### median
print('median of elements in array is',np.median(normal_array))

### sd
print('standard deviation of elements in array is',np.std(normal_array))

Array is [ 0  2  4  6  8 10]
min element is 0
max element is 10
sum of elements in array is 30
mean of element in array is 5.0
median of elements in array is 5.0
standard deviation of elements in array is 3.415650255319866
